languageName: "English"
contentDir: "content/en"
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 90
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 100
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 200
    - identifier: series
      name: series
      url: /series/
      weight: 290
    - identifier: search
      name: search
      url: /search/
      weight: 300
    - indentifier: about
      name: about
      url: /about/
      weight: 500
params:
  homeInfoParams:
    Content: >
      ğŸ‘‹ Welcome to Hawkeye-xb blog!
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # title: Hawkeye-xb Blog
  comments: true # å¯ç”¨è¯„è®ºæ¨¡å—
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  tocopen: false # å¯ç”¨æ–‡ç« ç›®å½•
  ShowWordCount: true
  ShowReadingTime: true
    
  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/hawkeye-xb/blog"
        