languageName: "ç®€ä½“ä¸­æ–‡(chinese)"
contentDir: "content/zh"
menu:
  main:
    - identifier: archives
      name: å½’æ¡£
      url: /archives/
      weight: 90
    # - identifier: categories
    #   name: ç±»åˆ«
    #   url: /categories/
    #   weight: 100
    - identifier: series
      name: ç³»åˆ—
      url: /series/
      weight: 290
    - identifier: search
      name: æœç´¢
      url: /search/
      weight: 300
    - indentifier: more
      name: æ›´å¤š
      url: /more
      weight: 900
params:
  homeInfoParams:
    Content: >
      ğŸ‘‹ æ¬¢è¿æ¥åˆ°Hawkeye-xb çš„åšå®¢å„¿!

  buildBlogSeriesName: "äº”åˆ†é’Ÿç³»åˆ—"
  buildBlogSeriesOpeningRemarks: "    \nå¤§å®¶å¥½ã€‚    \nä»Šå¤©æ¥ç€ç ”ç©¶ä¸ªäººç«™é•¿æ¢ç´¢ä¹‹åšå®¢æ­å»ºã€‚"
  flutterSeriesName: "Flutter ç³»åˆ—"

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # title: Hawkeye-xb Blog
  comments: true # å¯ç”¨è¯„è®ºæ¨¡å—
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  tocopen: false # å¯ç”¨æ–‡ç« ç›®å½•
  ShowWordCount: true
  ShowReadingTime: true
  hasCJKLanguage: true
  isCJKLanguage: true
    
  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/hawkeye-xb/blog"